REST_PORT: 8081
REST_HOST: "0.0.0.0"

POSTGRES:
  POSTGRES_HOST: postgres #"127.0.0.1"
  POSTGRES_PORT:  5432
  POSTGRES_USER: "root"
  POSTGRES_PASS: "1234"
  POSTGRES_DB: "postgres"
  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5
